states = ['BW', 'BY', 'BE', 'BB', 'HB', 'HH', 'HE', 'MV', 'NI', 'NW', 'RP', 'SL', 'SN', 'ST', 'SH', 'TH']

url = 'https://www.justiz-dolmetscher.de/Recherche/de/Suchen'
headers = {
    'authority': 'www.justiz-dolmetscher.de',
    'accept': 'application/json, text/javascript, */*; q=0.01',
    'accept-language': 'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,de;q=0.6,fr;q=0.5,sv;q=0.4',
    'content-type': 'application/x-www-form-urlencoded; charset=UTF-8',
    'cookie': 'ASP.NET_SessionId=1by3tlz0gyr1cpi0rduywyy4; language=en',
    'dnt': '1',
    'origin': 'https://www.justiz-dolmetscher.de',
    'referer': 'https://www.justiz-dolmetscher.de/Recherche/de/Suchen',
    'sec-ch-ua': '"Google Chrome";v="119", "Chromium";v="119", "Not?A_Brand";v="24"',
    'sec-ch-ua-mobile': '?0',
    'sec-ch-ua-platform': '"macOS"',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-origin',
    'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36',
    'x-requested-with': 'XMLHttpRequest',
}

data = {
    'sEcho': '2',
    'iColumns': '9',
    'sColumns': ',,,,,,,,',
    'mDataProp_0': 'PersonId',
    'sSearch_0': '',
    'bRegex_0': 'false',
    'bSearchable_0': 'false',
    'bSortable_0': 'true',
    'mDataProp_1': 'Nachname',
    'sSearch_1': '',
    'bRegex_1': 'false',
    'bSearchable_1': 'true',
    'bSortable_1': 'true',
    'mDataProp_2': 'Vorname',
    'sSearch_2': '',
    'bRegex_2': 'false',
    'bSearchable_2': 'true',
    'bSortable_2': 'true',
    'mDataProp_3': 'Sprachen',
    'sSearch_3': '',
    'bRegex_3': 'false',
    'bSearchable_3': 'true',
    'bSortable_3': 'true',
    'mDataProp_4': 'Plz',
    'sSearch_4': '',
    'bRegex_4': 'false',
    'bSearchable_4': 'true',
    'bSortable_4': 'true',
    'mDataProp_5': 'Ort',
    'sSearch_5': '',
    'bRegex_5': 'false',
    'bSearchable_5': 'true',
    'bSortable_5': 'true',
    'mDataProp_6': 'Strasse',
    'sSearch_6': '',
    'bRegex_6': 'false',
    'bSearchable_6': 'true',
    'bSortable_6': 'true',
    'mDataProp_7': 'Telefon',
    'sSearch_7': '',
    'bRegex_7': 'false',
    'bSearchable_7': 'true',
    'bSortable_7': 'true',
    'mDataProp_8': 'LetzteAenderung',
    'sSearch_8': '',
    'bRegex_8': 'false',
    'bSearchable_8': 'true',
    'bSortable_8': 'true',
    'sSearch': '',
    'bRegex': 'false',
    'iSortCol_0': '0',
    'sSortDir_0': 'asc',
    'iSortingCols': '1',
    'Sprache1': '',
    'Sprache2': '',
    'Plz': '',
    'Ort': '',
    'Nachname': '',
    'Behoerde': '0',
}
